#!/bin/bash

set -e

function usage {
    echo "Run AMQP message broker locally on port 5672"
    echo "Usage: $0 -t tag"
    echo "    tag : Docker image tag"
}

tag=""

OPTIND=1
while getopts "t:h" opt; do
    case $opt in
        t)
            tag=$OPTARG
            ;;
        h)
            usage ; exit 0
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            usage ; exit 1
            ;;
    esac
done

if [ -z "$tag" ]; then
    echo "Docker tag not specified" >&2
    usage ; exit 1
fi

docker run -d -p 5672:5672 "$tag" /usr/sbin/rabbitmq-server
